######################## default configuration ####################
baseURL = "https://www.therussianlullaby.com"
languageCode = "en-us"
title = "The Russian Lullaby"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = "therussianlullaby"

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "The Russian Lullaby: Drupal tips and articles about web development."
author = "@davidjguru"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = "(skype) - davidjguru"
email = "info@therussianlullaby.com"
location = "Sevilla, Andalusia (Spain)"
# copyright
copyright = "| copyleft for contents - CC BY-NC-SA | copyright for Layout [Themefisher](https://themefisher.com) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"

############################# social site ########################

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/davidjguru"

[[params.social]]
title = "blog"
icon = "ti-pencil" # themify icon : https://themify.me/themify-icons
link = "https://davidjguru.github.io/"

[[params.social]]
title = "gitlab"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://gitlab.com/davidjguru"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/davidjguru/"

[[params.social]]
title = "drupal"
icon = "ti-drupal" # themify icon : https://themify.me/themify-icons
link = "https://www.drupal.org/u/davidjguru"

