######################## default configuration ####################
baseURL = "https://www.therussianlullaby.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "The Russian Lullaby"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
enableRobotsTXT = true
disqusShortname = "therussianlullaby"

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "The Russian Lullaby: Drupal tips and articles about web development."
author = "@davidjguru"
# Google Analitycs
googleAnalitycsID = "UA-162823320-1"
# Contact Information
mobile = "(skype) - davidjguru"
email = "info@therussianlullaby.com"
location = "Sevilla, Andalusia (Spain)"
# Sharing key
addThis = "ra-5f05a60441f224f8"
# copyright
copyright = "| Creative Commons License for contents - [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/3.0/) | Copyright for Layout - [Themefisher](https://themefisher.com) |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Join to the (Future) Newsletter"
content = "De la pradera tiene musho peligro al ataquerl te voy a borrar el cerito torpedo tiene musho peligro pupita al ataquerl diodeno. Torpedo ese pedazo de qué dise usteer a peich ese que llega la caidita pecador."

############################# social site ########################

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/davidjguru"

[[params.social]]
title = "blog"
icon = "ti-pencil" # themify icon : https://themify.me/themify-icons
link = "https://davidjguru.github.io/"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/davidjguru"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/davidjguru/"

[[params.social]]
title = "drupal"
icon = "ti-drupal" # themify icon : https://themify.me/themify-icons
link = "https://www.drupal.org/u/davidjguru"

